### PR TITLE
Fix #316 polymorphic create fragment

### LINKED ISSUE #316: FragmentArray.createFragment should respect `type` in polymorphic arrays
If I have polymorphic fragment array:

```js
export MyModel = DS.Model.extend({
  parts: MF.fragmentArray('part', { polymorphic: true }),
});
```

with hierarchic fragment models:
```js
export Part = MF.Fragment.extend({
  // ...
}

export PartOne = Part.extend({
  // ...
}

```

And then I want to create fragment directly on the array, with given type:

```js
myModel.get('parts').createFragment({
  type: 'part-one',
  fields: ...
});
```

It does not respect the type passed. Rather it always creates the fragment with the type declared in the definition of the `fragmentArray`. As it can be seen in the code here:

https://github.com/lytics/ember-data-model-fragments/blob/master/addon/array/fragment.js#L244

Is there reason for this? Would it make sense to look for the `typeKey` in the given object to `createFragment` and use that if the array definition is polymorphic?

### PR DESCRIPTION
**Pull request by dwickern**
I fixed the merge conflicts from #436 and got it working with the new RecordData implementation.

Fixes #316
Closes #436

### CODE REVIEW

**Comment by dwickern** [comment]
There seems to be a problem still with polymorphic values in fragmentArrays when using `createRecord`:
```js
const zoo = store.createRecord('zoo', {
  star: { $type: 'lion' },
  animals: [{ $type: 'lion' }, { $type: 'elephant' }],
});
zoo.star instanceof Lion; // true
zoo.animals.firstObject instanceof Lion; // false
zoo.animals.lastObject instanceof Elephant; // false
```

**Comment by knownasilya** [comment]
@dwickern ready for review?

**Comment by dwickern** [comment]
@knownasilya ready for review 👍

**Review by knownasilya — APPROVED** [review]
Nice

**Comment by dwickern** [comment]
@knownasilya any plans to release this fix?

**Comment by knownasilya** [comment]
@dwickern released

**Pull request merged**
