### PR TITLE
add parent record to default value function

### PR DESCRIPTION
**Pull request by VincentMolinie**

### CODE REVIEW

**Comment by knownasilya** [comment]
ping

**Comment by knownasilya** [comment]
@VincentMolinie I can merge once feedback is addressed

**Comment by dwickern** [comment]
This was implemented by #417. The fragment attributes' `defaultValue` has the same signature as ember-data's `attr`.
`defaultValue: (record, options, key) => ...`

**Comment by VincentMolinie** [comment]
Yeah sorry I don't have time, I'll take care of

**Pull request closed without merging**
